# Linear Algebra for CpE
# Laboratory 6: Matrices

###### Coded and submitted by:

###### Estocapio, Dean Adrian N.

##### 58011

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## Activity

### Task 1

In [124]:
def mat_desc(matrix):
    if matrix.size > 0:
        print("The matrix is not null\n")
        print("The given matrix is:\n",matrix)
        print("\nThe shape of the matrix is:",matrix.shape)
        print("The size of the matrix is:", matrix.size)
        print("The rank of the matrix is:",matrix.ndim)
        
        if matrix.shape[0] == matrix.shape[1]: 
            print("The given matrix is a square")
            if (matrix==np.eye(matrix.shape[0])).all():
                print("The given matrix is an Identity matrix")
            elif np.count_nonzero(matrix) == 0:
                print("The given matrix is a zeros matrix")
            elif np.all(matrix == 1):
                print("The given matrix is a ones matrix")
            else:
                print("The given matrix is neither a zeros, identity, or ones")
        else:
            print("The given matrix is not a square")
            if np.count_nonzero(matrix) == 0:
                print("The given matrix is a zeros matrix")
            elif np.all(matrix == 1):
                print("The given matrix is a ones matrix")
            else:
                print("The given matrix is neither a zeros, identity, or ones")

    else:
        print("The matrix is empty")
    print("=================================================")

In [125]:
A = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
B = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])
C = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
D = np.array([
    [1,5,0],
    [0,4,9],
    [4,5,6]
])
E = np.array([
    [5,5,2],
    [6,5,2],
    [2,6,1],
    [1,8,4]
])

In [126]:
mat_desc(A)
mat_desc(B)
mat_desc(C)
mat_desc(D)
mat_desc(E)

The matrix is not null

The given matrix is:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The given matrix is a square
The given matrix is a ones matrix
The matrix is not null

The given matrix is:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The given matrix is a square
The given matrix is a zeros matrix
The matrix is not null

The given matrix is:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The given matrix is a square
The given matrix is an Identity matrix
The matrix is not null

The given matrix is:
 [[1 5 0]
 [0 4 9]
 [4 5 6]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The given matrix is a square
The given matrix is neither a zeros, identity, or ones
The matrix is not null

The given matrix is:
 [[5

In [10]:
def mat_operations(A,B):
    if A.shape == B.shape:
        print("The sum of the two is:\n", A+B)
        print("The difference of the two is:\n", A-B)
        print("The product of the two is:\n", A*B)
        print("The quotient of the two is:\n", A/B)
    else:
        print("The two given are unequal, and are not viable for operations")
    print("=================================================")
        


In [ ]:
A = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
B = np.array([
    [5,5,2],
    [6,5,2],
    [2,6,1]
])

mat_operations(A,B)