In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#### The Six Properties of Matrix Multiplication
The commutative property of multiplication does not hold	$$AB\neq BA$$
Associative property of multiplication	$$(AB)C=A(BC)$$
Distributive properties	$$A(B+C)=AB+AC\\(B+C)A=BA+CA$$
Multiplicative identity property	$$IA=A\\AI=A$$
Multiplicative property of zero	$$OA=O\\AO=O$$
Dimension property	The product of an $$mxn$$ matrix and an $$n×k$$ is an $$mxk$$

In [2]:
A = np.array([
    [3, 4, 5],
    [2, 3, 3],
    [3, 3, 4]
])
B = np.array([
    [6, 8, 1],
    [5, 9, 2],
    [5, 2, 3]
])
C = np.array([
    [4, 9, 4],
    [3, 1, 6],
    [2, 5, 2]
])
D = np.array([
    [4, 9, 3,6],
    [3, 4, 1,4],
    [8, 3, 3,2]
])
E = np.array([
    [4, 2, 1],
    [1, 9, 6],
    [2, 2, 2],
    [3, 4, 5]
])
I = np.identity(3)
O = np.zeros([3,3])

#### 1.) The commutative property of multiplication does not hold

In [3]:
First = A@B
Second = B@A
print("Result of AB is:\n",First)
print("Result of BA is:\n",Second)
print("Equality is:", np.array_equal(First,Second))

Result of AB is:
 [[63 70 26]
 [42 49 17]
 [53 59 21]]
Result of BA is:
 [[37 51 58]
 [39 53 60]
 [28 35 43]]
Equality is: False


#### 2.) Associative property of multiplication

In [4]:
FirstAsso  = (A@B)@C
SecondAsso = 𝐴@(𝐵@𝐶)
print("Result of (AB)C is:\n",FirstAsso)
print("Result of A(BC) is:\n",SecondAsso)
print("Equality is:", np.array_equal(FirstAsso,SecondAsso))

Result of (AB)C is:
 [[514 767 724]
 [349 512 496]
 [431 641 608]]
Result of A(BC) is:
 [[514 767 724]
 [349 512 496]
 [431 641 608]]
Equality is: True


#### 3.) Distributive properties

In [5]:
FirstDistri = A@(B+C)
SecondDistri = (A@B)+(A@C)
print("Result of A(B+C) is:\n",FirstDistri)
print("Result of (AB)+(AC) is:\n",SecondDistri)
print("Equality is:", np.array_equal(FirstDistri,SecondDistri))
print("\n")
ThirdDistri = (B+C)@A
FourthDistri = (B@A)+(C@A)
print("Result of (B+C)A is:\n",ThirdDistri)
print("Result of (BA)+(CA) is:\n",FourthDistri)
print("Equality is:", np.array_equal(ThirdDistri,FourthDistri))

Result of A(B+C) is:
 [[ 97 126  72]
 [ 65  85  49]
 [ 82 109  59]]
Result of (AB)+(AC) is:
 [[ 97 126  72]
 [ 65  85  49]
 [ 82 109  59]]
Equality is: True


Result of (B+C)A is:
 [[ 79 106 121]
 [ 68  86 102]
 [ 50  64  76]]
Result of (BA)+(CA) is:
 [[ 79 106 121]
 [ 68  86 102]
 [ 50  64  76]]
Equality is: True


#### 4.) Multiplicative identity property

In [6]:
FirstIden = A@I
SecondIden = I@A
print("Result of AI is:\n",FirstIden)
print("Equality is:", np.array_equal(FirstIden,A))
print("\n")
print("Result of IA is:\n",SecondIden)
print("Equality is:", np.array_equal(SecondIden,A))

Result of AI is:
 [[3. 4. 5.]
 [2. 3. 3.]
 [3. 3. 4.]]
Equality is: True


Result of IA is:
 [[3. 4. 5.]
 [2. 3. 3.]
 [3. 3. 4.]]
Equality is: True


#### 5.) Multiplicative property of zero

In [7]:
FirstZero = A@O
SecondZero = O@A
print("Result of AO is:\n",FirstZero)
print("Result of OA is:\n",SecondZero)

Result of AO is:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Result of OA is:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 6.) Dimension Property

In [8]:
FirstDimen = D@E
print("The shape of Matrix D is:", D.shape)
print("The shape of Matrix E is:", E.shape)
print("The Shape of their product must be:", "(", D.shape[0], ",", E.shape[1], ")")
print(FirstDimen)

The shape of Matrix D is: (3, 4)
The shape of Matrix E is: (4, 3)
The Shape of their product must be: ( 3 , 3 )
[[ 49 119  94]
 [ 30  60  49]
 [ 47  57  42]]
