# Linear Algebra for CpE
# Laboratory 6: Matrices

###### Coded and submitted by:

###### Estocapio, Dean Adrian N.

##### 58011

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## Activity

### Task 1

In [2]:
def mat_desc(matrix):
    if matrix.size > 0:
        print("The matrix is not null\n")
        print("The given matrix is:\n",matrix)
        print("\nThe shape of the matrix is:",matrix.shape)
        print("The size of the matrix is:", matrix.size)
        print("The rank of the matrix is:",matrix.ndim)
        
        if matrix.shape[0] == matrix.shape[1]: 
            print("The given matrix is a square")
            if (matrix==np.eye(matrix.shape[0])).all():
                print("The given matrix is an Identity matrix")
            elif np.count_nonzero(matrix) == 0:
                print("The given matrix is a zeros matrix")
            elif np.all(matrix == 1):
                print("The given matrix is a ones matrix")
            else:
                print("The given matrix is neither a zeros, identity, or ones")
        else:
            print("The given matrix is not a square")
            if np.count_nonzero(matrix) == 0:
                print("The given matrix is a zeros matrix")
            elif np.all(matrix == 1):
                print("The given matrix is a ones matrix")
            else:
                print("The given matrix is neither a zeros, identity, or ones")

    else:
        print("The matrix is empty")
    print("=================================================")

In [3]:
A = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
B = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])
C = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
D = np.array([
    [1,5,0],
    [0,4,9],
    [4,5,6]
])
E = np.array([
    [5,5,2],
    [6,5,2],
    [2,6,1],
    [1,8,4]
])

In [4]:
mat_desc(A)
mat_desc(B)
mat_desc(C)
mat_desc(D)
mat_desc(E)

The matrix is not null

The given matrix is:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The given matrix is a square
The given matrix is a ones matrix
The matrix is not null

The given matrix is:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The given matrix is a square
The given matrix is a zeros matrix
The matrix is not null

The given matrix is:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The given matrix is a square
The given matrix is an Identity matrix
The matrix is not null

The given matrix is:
 [[1 5 0]
 [0 4 9]
 [4 5 6]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
The given matrix is a square
The given matrix is neither a zeros, identity, or ones
The matrix is not null

The given matrix is:
 [[5

In [5]:
def mat_operations(A,B):
    if A.shape == B.shape:
        print("The sum of the two is:\n", A+B)
        print("The difference of the two is:\n", A-B)
        print("The product of the two is:\n", A*B)
        print("The quotient of the two is:\n", A/B)
    else:
        print("The two given are unequal, and are not viable for operations")
    print("=================================================")
        


In [10]:
F = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
G = np.array([
    [5,5,2],
    [6,5,2],
    [2,6,1]
])
H = np.array([
    [3,1,4],
    [1,3,5],
    [4,6,8]
])
J = np.array([
    [5,3,1],
    [9,5,3],
    [7,5,5]
])
K = np.array([
    [4,8,6],
    [5,8,7],
    [4,8,8]
])


mat_operations(F,G)
mat_operations(H,J)
mat_operations(J,K)

The sum of the two is:
 [[6 6 3]
 [7 6 3]
 [3 7 2]]
The difference of the two is:
 [[-4 -4 -1]
 [-5 -4 -1]
 [-1 -5  0]]
The product of the two is:
 [[5 5 2]
 [6 5 2]
 [2 6 1]]
The quotient of the two is:
 [[0.2        0.2        0.5       ]
 [0.16666667 0.2        0.5       ]
 [0.5        0.16666667 1.        ]]
The sum of the two is:
 [[ 8  4  5]
 [10  8  8]
 [11 11 13]]
The difference of the two is:
 [[-2 -2  3]
 [-8 -2  2]
 [-3  1  3]]
The product of the two is:
 [[15  3  4]
 [ 9 15 15]
 [28 30 40]]
The quotient of the two is:
 [[0.6        0.33333333 4.        ]
 [0.11111111 0.6        1.66666667]
 [0.57142857 1.2        1.6       ]]
The sum of the two is:
 [[ 9 11  7]
 [14 13 10]
 [11 13 13]]
The difference of the two is:
 [[ 1 -5 -5]
 [ 4 -3 -4]
 [ 3 -3 -3]]
The product of the two is:
 [[20 24  6]
 [45 40 21]
 [28 40 40]]
The quotient of the two is:
 [[1.25       0.375      0.16666667]
 [1.8        0.625      0.42857143]
 [1.75       0.625      0.625     ]]
